### PR TITLE
Update travis config to use full suite of Moodle tests.

### PR DESCRIPTION
**Pull request by danmarsden**
there's a wide range of Moodle tests that can be run in travis-ci now, including coding guideline/behat/various other tests. This file uses the latest version of the tests now available - (I expect to see lots of failures due to non-compliance to Moodle coding guidelines within the code.)

Note - this pull request should trigger the Travis ci tests and we should be able to see the results here shortly.

### CODE REVIEW

**Comment by danmarsden** [comment]
looks like travis config is configured to disable travis on pull requests - would be good to get that changed if possible?
https://travis-ci.org/elearningsoftware/moodle-mod_journal/requests

**Comment by adrian-sarmas** [comment]
I've enabled travis on pull requests. @danmarsden could you have a look at the .travis.yml file and help me get it right? It does not pass the tests on php 5.6, but it does on php 7.

**Comment by danmarsden** [comment]
awesome! - great to see some progress on this - thanks heaps!

the master moodle branch doens't support PHP 5.6 - it only supports PHP 7.0 and higher so you should remove the 5.6 checks from the travis config:
https://docs.moodle.org/dev/Moodle_3.4_release_notes#Server_requirements

**Comment by adrian-sarmas** [comment]
Thanks for your help @danmarsden . I still have some issues with travis.

I removed php 5.6 from master branch. Now I have another issue since I get no pass for the latest commit on the MOODLE_31_STABLE branch: **The command "moodle-plugin-ci install" failed and exited with 1**.

Is this an issue with the moodle-plugin-ci plugin or the .travis.yml file?
Could you have a look at https://travis-ci.org/elearningsoftware/moodle-mod_journal/jobs/312421806 ?

**Pull request merged**
