### PR TITLE
Add necessary function return types to privacy provider implementation

### LINKED ISSUE #47: Missing return types for privacy methods
Currently the two methods
`public static function get_metadata(collection $collection) : collection `
`public static function get_contexts_for_userid(int $userid) : contextlist`
do not specify the return types as above. Since at least in moodle 3.7 these return types are present at the parent class, this leads to a nasty error when deleting (and probably also exporting) user data. It is nasty, since the error is not really visible in the cron logs.

### PR DESCRIPTION
**Pull request by tobiasreischmann**
Fixes #47

### CODE REVIEW

**Comment by Urpokarhu1** [comment]
Hello,

We have tested this fix and it works, can you add it to the master? @tobiasreischmann

**Comment by tobiasreischmann** [comment]
I am not allowed to merge anything, unfortunately.

**Comment by adrian-sarmas** [comment]
Thanks @tobiasreischmann. I did notice Travis build fails for your pull request. Could you also edit `.travis.yml` to make this build pass?

**Comment by tobiasreischmann** [comment]
Sorry for the delay. I adjusted the travis.yml.
I removed php 5.6 and 7.1 since they are out of support. 
Further, the patch breaks with php 5.6 since return types were introduced with php 7.0.
Thus, php 5.6 support should be removed for the next release version.
The moodle versions that I removed are due to the fact that they do not support the respective php version.

**Comment by danmarsden** [comment]
Great! - thanks for that! - makes our job a lot easier when we can use the upstream repo rather than having to maintain a fork.

**Pull request merged**
